### ISSUE TITLE
B13.1 Prep IM and LDDTool for new IM Version

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds4-information-model#513]
## 💡 Description

New task to be created for every build to ensure LDDTool versioning updates are supported correct.

 - [ ] update LDDTool default version
 - [ ] update LDDTool -V to support new version
 - [ ] add latest PDS4 IM to new directory in repo

**Comment by jordanpadams** [comment]
📆 February status: Task start awaiting completion of https://github.com/nasa-pds/pds4-information-model/issues/547. No schedule impact foreseen.

**Comment by jordanpadams** [comment]
@jshughes per the last task in this ticket, I think we should start including the XSD/SCH/etc. in the repo for when we add support for new IM versions so they will also be tagged in releases of the repo. similar to the products you email the ops team. this way we can direct users to the repo for testing the new version, while also allowing us the ability to update the repo. thoughts?

**Comment by jshughes** [comment]
Sounds good, however, I just want to confirm what needs to be done in addition to what is normally done for the release of the IM. Currently the following items have been completed prior to the IM release.
1. update LDDTool default version
2. update LDDTool -V to support new version
3. add latest PDS4 IM to new directory in repo

I could resolve the open issue, e.g.,  "B13.1 Prep IM and LDDTool for new IM Version #513", in the last PR.  However, the last PR could either involve LDDTool or the IM. Typically the LDDTool has the above items completed long before the IM is ready.  

An alternative might be to create new  PR associated with depositing the .xsd, .sch, etc files in the repository. I was thinking of adding the folder /schema to the /docs folder.

**Comment by jordanpadams** [comment]
@jshughes it looks like the schemas/schematrons were added to the repo for 1K00, but your updates to LDDTool to set the default version of 1K00 never took. can you add this to the top of your list?
